# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2023-05-09 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SD_Host',
            fields=[
                ('ip', models.CharField(default='fang', max_length=16, primary_key=True, serialize=False, verbose_name='sd服务主机ip')),
                ('port', models.CharField(max_length=16, null=True, verbose_name='sd服务主机port')),
                ('status', models.IntegerField(max_length=11, null=True, verbose_name='0：关闭，1: 开启')),
            ],
            options={
                'verbose_name': 'sd主机信息',
                'verbose_name_plural': 'sd主机信息',
                'db_table': 'sd_host',
            },
        ),
        migrations.CreateModel(
            name='SD_Task_Process',
            fields=[
                ('ip', models.CharField(default='fang', max_length=16, primary_key=True, serialize=False, verbose_name='sd服务主机ip')),
                ('port', models.CharField(max_length=16, null=True, verbose_name='sd服务主机port')),
                ('task_id', models.CharField(max_length=55, null=True, verbose_name='task_id')),
                ('status', models.IntegerField(max_length=11, null=True, verbose_name='0：关闭，1: 开启')),
                ('pic_description', models.TextField(blank=True, null=True, verbose_name='图片信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'sd处理过程数据',
                'verbose_name_plural': 'sd处理过程数据',
                'db_table': 'sd_task_process',
            },
        ),
    ]
