# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2023-05-09 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sd_host',
            name='status',
            field=models.IntegerField(default=0, verbose_name='0：关闭，1: 开启'),
        ),
        migrations.AlterField(
            model_name='sd_task_process',
            name='status',
            field=models.IntegerField(default=0, verbose_name='0：关闭，1: 开启'),
        ),
    ]
