# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2023-05-09 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_interface', '0003_sd_task_process_rqbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sd_task_process',
            name='ip',
            field=models.CharField(default='ip', max_length=16, null=True, verbose_name='sd服务主机ip'),
        ),
        migrations.AddField(
            model_name='sd_task_process',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

    ]
