# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-05-09 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_interface', '0004_auto_20230509_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sd_task_process',
            name='rqbody',
            field=models.TextField(blank=True, default=1, verbose_name='请求体'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sd_task_process',
            name='task_id',
            field=models.CharField(default=1, max_length=55, verbose_name='task_id'),
            preserve_default=False,
        ),
    ]
