# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-05-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_interface', '0005_auto_20230509_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='sd_task_process',
            name='service_type',
            field=models.IntegerField(default=0, verbose_name='0：txt2img，1: img2img'),
        ),
    ]
